### ISSUE TITLE
Which function can be used to upload images?

### ISSUE THREAD

**Issue by zhaoguangyuan123** [SivyerLab/pyCrafter4500#10]
Hi,

I cannot find which single function inside this repo is for uploading images. Could the author show an example with .png figure?

Thanks  a lot

**Comment by arrrobase** [comment]
I'm glad you're finding pyCrafter4500 useful. Our lab mostly used this code to switch between the different LEDs of the light engine and the frame rate, as well as turning it on or off for various experiments, so I don't really have any experience with loading bitmaps into memory and getting that working. 

Here's a link to the documentation I referred to when creating this [library](https://www.ti.com/lit/ug/dlpu010g/dlpu010g.pdf).

I'm not sure how to programmatically get images loaded onto the onboard memory, but this [example](https://github.com/csi-dcsc/Pycrafter6500/blob/master/pycrafter6500.py#L366) from Pycrafter6500 might help point you in the right direction.

I believe it's using the equivalent of the "send_pattern_lut" command to load in a bitmap to the right memory address, but it's been several years since I've worked on this code or with the DLP.

**Comment by zhaoguangyuan123** [comment]
Thank you, Alexander!

I actually was coming from the repo of Pycrafter6500 that you referred.
I can upload bitmap use the Pycrafer6500 but the issue is the speed is quite slow.
So I was wondering if you have offered a faster way or know some faster way of uploading pattern.

Best
Guangyuan
